### ISSUE TITLE
Problem with standard example

### ISSUE THREAD

**Issue by matteoteknet** [eymengunay/php-passbook#58]
Hello to all,

I followed the instruction (composer, example, ...)
But when i test my script with phpunit always i get stucked with this error.

`PHP Fatal error:  Uncaught Error: Class 'Passbook\Type\EventTicket' not found in /var/www/html/webapp/passbook.php:25
Stack trace:
#0 /usr/share/php/PHPUnit/Util/Fileloader.php(56): include_once()
#1 /usr/share/php/PHPUnit/Util/Fileloader.php(38): PHPUnit_Util_Fileloader::load('/var/www/html/w...')
#2 /usr/share/php/PHPUnit/Runner/StandardTestSuiteLoader.php(39): PHPUnit_Util_Fileloader::checkAndLoad('/var/www/html/w...')
#3 /usr/share/php/PHPUnit/Runner/BaseTestRunner.php(124): PHPUnit_Runner_StandardTestSuiteLoader->load('passbook', '/var/www/html/w...')
#4 /usr/share/php/PHPUnit/Runner/BaseTestRunner.php(65): PHPUnit_Runner_BaseTestRunner->loadSuiteClass('passbook', '/var/www/html/w...')
#5 /usr/share/php/PHPUnit/TextUI/Command.php(128): PHPUnit_Runner_BaseTestRunner->getTest('passbook', '/var/www/html/w...', Array)
#6 /usr/share/php/PHPUnit/TextUI/Command.php(106): PHPUnit_TextUI_Command->run(Array, true)
#7 /usr/bin/phpunit(29): PHPUnit_TextUI_Command::main()
#8 {main}
  thrown in /var/www/html/webapp/passbook.php on line 25
`

my folder structure is

- passbook.php
- src
--- Passbook
------ ...
- vendor

i think there are problem with composer or autoload, but i can't figure how to solve it! Any suggestion?
Thank you!

**Comment by matteoteknet** [comment]
Hello to all,

I just solved my problem, composer can't autoload the Passbook library.

i've added 
`require 'vendor/autoload.php';`

before all other inclusions.
Thanks.
